[workspace]
members = [
    "crates/yunxi-agent-core",
    "crates/yunxi-agent-companion",
    "crates/yunxi-agent-eval",
    "crates/yunxi-agent-protocol",
    "crates/yunxi-agent-provider",
    "crates/yunxi-agent-context",
    "crates/yunxi-agent-persona",
    "crates/yunxi-agent-sandbox",
    "crates/yunxi-agent-exec",
    "crates/yunxi-agent-patch",
    "crates/yunxi-agent-tools",
    "crates/yunxi-agent-mcp",
    "crates/yunxi-agent-skills",
    "crates/yunxi-agent-multi-agent",
    "crates/yunxi-agent-storage",
    "crates/yunxi-agent-runtime",
    "crates/yunxi-agent-tui",
    "crates/yunxi-agent-weixin",
    "crates/yunxi-agent-voice",
    "crates/yunxi-agent-cli",
    "yunxi-agent-archlinux",
]
default-members = [
    "crates/yunxi-agent-core",
    "crates/yunxi-agent-companion",
    "crates/yunxi-agent-eval",
    "crates/yunxi-agent-protocol",
    "crates/yunxi-agent-provider",
    "crates/yunxi-agent-context",
    "crates/yunxi-agent-persona",
    "crates/yunxi-agent-sandbox",
    "crates/yunxi-agent-exec",
    "crates/yunxi-agent-patch",
    "crates/yunxi-agent-tools",
    "crates/yunxi-agent-mcp",
    "crates/yunxi-agent-skills",
    "crates/yunxi-agent-multi-agent",
    "crates/yunxi-agent-storage",
    "crates/yunxi-agent-runtime",
    "crates/yunxi-agent-tui",
    "crates/yunxi-agent-weixin",
    "crates/yunxi-agent-voice",
    "crates/yunxi-agent-cli",
    "yunxi-agent-archlinux",
]
resolver = "2"
exclude = ["external/codex-rs", "vendor/codex-rs", "crates/yunxi-agent-codex"]

[workspace.package]
edition = "2024"
license = "Apache-2.0"
version = "2.3.3-hotfix.32"
[workspace.dependencies]
aes = "0.8"
anyhow = "1"
async-trait = "0.1"
assert_cmd = "2"
axum = "0.8"
base64 = "0.22"
clap = { version = "4", features = ["derive"] }
chacha20poly1305 = "0.10"
ecb = { version = "0.1", features = ["alloc"] }
predicates = "3"
futures-util = "0.3"
crossterm = "0.28"
cpal = "0.16"
hound = "3.5.1"
httpdate = "1"
ratatui = "0.29"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "stream"] }
rusqlite = { version = "0.32", features = ["bundled"] }
rodio = { version = "0.21.1", default-features = false, features = ["playback", "wav"] }
reedline = "0.36"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3"
thiserror = "2"
tokio = { version = "1", features = ["io-util", "macros", "net", "process", "rt-multi-thread", "signal", "sync", "time"] }
unicode-segmentation = "1"
unicode-width = "0.2"
wiremock = "0.6"
getrandom = "0.3"
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Security_Credentials", "Win32_Storage_FileSystem", "Win32_System_Threading"] }
silk-decoder-rs = "0.1"

[profile.dev]
debug = 1

[profile.test]
debug = 1
