[package]
name = "yunxi-agent-tui"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
crossterm.workspace = true
ratatui.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true
yunxi-agent-core = { path = "../yunxi-agent-core" }
