[package]
name = "yunxi-agent-provider"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
futures-util.workspace = true
httpdate.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
yunxi-agent-core = { path = "../yunxi-agent-core" }
yunxi-agent-protocol = { path = "../yunxi-agent-protocol" }
yunxi-agent-tools = { path = "../yunxi-agent-tools" }

[dev-dependencies]
tempfile.workspace = true
tokio.workspace = true
