[package]
name = "yunxi-agent-exec"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
serde.workspace = true
tokio.workspace = true
yunxi-agent-core = { path = "../yunxi-agent-core" }
yunxi-agent-sandbox = { path = "../yunxi-agent-sandbox" }

[dev-dependencies]
tempfile.workspace = true
